kind: pipeline
type: kubernetes
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang:1.15
    environment:
      CGO_ENABLED: 0
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - go test -v ./... -cover
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

  - name: docker-tag
    image: alpine
    commands:
      - test "${DRONE_BRANCH}" == "master" && echo "latest" > .tags
      - test "${DRONE_BRANCH}" != "master" && echo "${DRONE_BRANCH}" > .tags
      - test "${DRONE_TAG}" != "" && echo ",${DRONE_TAG}" >> .tags

  - name: docker-publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/utilitywarehouse/drone-test-project
      registry: quay.io
