builds:
  - id: main
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: main
    builds:
      - main
    format: binary
    files:
      - none*
release:
  github:
    owner: george-angel
    name: drone-test-project
